# -*- coding: utf-8 -*-
"""Project 114.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p4BdjmHyBEwpvGsA1WARiV-_m3wtlf45
"""

import csv
import pandas as pd
import plotly.express as px
import numpy as np

from google.colab import files
filesToUpload = files.upload()

df = pd.read_csv("data.csv")
TOEFL = df["TOEFL Score"].tolist()
COA  = df["Chance of Admit "].tolist()

TOEFL = np.array(TOEFL)
COA = np.array(COA)

m,c = np.polyfit(TOEFL, COA, 1)

y = []

for x in TOEFL:
  y_value = m*x + c
  y.append(y_value)

fig = px.scatter(x = TOEFL, y = COA)
fig.update_layout(shapes = [
  dict(
      type = "line",
      y0 = min(y), y1 = max(y),
      x0 = min(TOEFL), x1 = max(TOEFL)
  )
])
fig.show()


x = 500
y = m*x + c
print(f"Chances of admission with the TOEFL score {x} is : {y}")